from airflow import DAG
from airflow.operators.bash import BashOperator
from pendulum import DateTime, Timezone
with DAG(dag_id='da_prod_data_and_analytics_daily', schedule=None, start_date=DateTime(1970, 1, 1, 0, 0, 0), catchup=False):
    da_prod_sotday_task = BashOperator(task_id='da_prod_sotday', bash_command='echo "Start of the day- my ecsd var: ECSD - SLACK_DA"', owner='ctmuser', doc='Start of the day job')
    da_prod_ctm_ciw_ingestion_monitor_coles_bucket_1_task = BashOperator(task_id='da_prod_ctm_ciw_ingestion_monitor_coles_bucket_1', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git   -s CIW_Ingestion_Monitor/Daily_Buckets_Monitor_jobs/CIW_Ingestion_Monitor_coles_bucket_1.R', owner='ctmuser', doc='This job checks whether CIW ingestion for the bucket-1 transaction tables is completed or not for the day')
    da_prod_ctm_cdm_ingestion_monitor_bucket_1_task = BashOperator(task_id='da_prod_ctm_cdm_ingestion_monitor_bucket_1', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git   -s CIW_Ingestion_Monitor/Daily_Buckets_Monitor_jobs/CDM_Ingestion_Monitor_bucket_1.R', owner='ctmuser', doc='This job checks whether CDW ingestion for the bucket-1 tables is completed or not for the day')
    da_prod_ctm_ciw_ingestion_monitor_coles_bucket_2_task = BashOperator(task_id='da_prod_ctm_ciw_ingestion_monitor_coles_bucket_2', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git   -s CIW_Ingestion_Monitor/Daily_Buckets_Monitor_jobs/CIW_Ingestion_Monitor_coles_bucket_2.R', owner='ctmuser', doc='This job checks whether CIW ingestion for the bucket-2 tables is completed or not for the day')
    da_prod_ctm_cdm_ingestion_monitor_bucket_3_task = BashOperator(task_id='da_prod_ctm_cdm_ingestion_monitor_bucket_3', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git   -s CIW_Ingestion_Monitor/Daily_Buckets_Monitor_jobs/CDM_Ingestion_Monitor_bucket_3.R', owner='ctmuser', doc='This job checks whether CDM ingestion for the bucket-3 tables is completed or not for the day')
    da_prod_ctm_fb_12_month_active_mbr_task = BashOperator(task_id='da_prod_ctm_fb_12_month_active_mbr', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s Active_Members/12_MONTH_ACTIVE_TABLE.r', owner='ctmuser', doc='Run the Active 12month MBR daily Job')
    da_prod_ctm_fb_active_12_m_mbr_cs_export_task = BashOperator(task_id='da_prod_ctm_fb_active_12_m_mbr_cs_export', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s Active_Members/12_MONTH_ACTIVE_EXPORT.r', owner='ctmuser', doc='This job exports the ACTIVE_12M_MBR_CS table to csv in s3 bucket for coles')
    da_prod_ctm_fb_12_month_active_cardholder_task = BashOperator(task_id='da_prod_ctm_fb_12_month_active_cardholder', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s Active_Cardholders/CTM_PA_12month_cardholderactive_table.R', owner='ctmuser', doc='Run the Active 12month Cardholder daily Job')
    da_prod_ctm_fb_12month_active_volume_mail_notif_task = BashOperator(task_id='da_prod_ctm_fb_12month_active_volume_mail_notif', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s Active_Cardholders/12month_active_volume_MailNotif.r', owner='ctmuser', doc='Run the Active 12month email notification Job')
    da_prod_ctm_flybuys_travel_data_refresh_task = BashOperator(task_id='da_prod_ctm_flybuys_travel_data_refresh', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s flybuys_Travel_Data/flybuysTravelDataRefresh_Main_CURRENT.r', owner='ctmuser', doc='Run the daily flybuys travel data Refresh  Job')
    da_prod_ctm_travel_search_trigger_task = BashOperator(task_id='da_prod_ctm_travel_search_trigger', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git                      -s flybuys_Travel_Triggers/TV0124_PT_TRAVEL_TRIGGER.r', owner='ctmuser', doc='Flybuys Travel Trigger job')
    da_prod_ctm_flybuys_travel_customer_journey_main_task = BashOperator(task_id='da_prod_ctm_flybuys_travel_customer_journey_main', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/software_redevelopment/part.git -s Load_flybuys_CX_Journey/LOAD_TV0283_CX_JOURNEY.sql', owner='ctmuser', doc='Run the flybuysTravelCustomerJourney_Main job')
    da_prod_ctm_flybuys_travel_customer_journey_mail_notification_task = BashOperator(task_id='da_prod_ctm_flybuys_travel_customer_journey_mail_notification', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/part.git -s Load_flybuys_CX_Journey/flybuysTravelCustomerJourney_MailNotif_CURRENT.R', owner='ctmuser', doc='Run the flybuysTravelCustomerJourney_MailNotification')
    da_prod_ctm_rfm_coles_scoring_main_task = BashOperator(task_id='da_prod_ctm_rfm_coles_scoring_main', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s RFM_Coles/LOAD_PR0191_COLES_RFM_SCORING.sql', owner='ctmuser', doc='Run the RFM Coles Scoring main script')
    da_prod_ctm_rfm_coles_scoring_mail_notification_task = BashOperator(task_id='da_prod_ctm_rfm_coles_scoring_mail_notification', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s RFM_Coles/RFMColesScoring_MailNotif_CURRENT.r', owner='ctmuser', doc='Run the RFM Coles Scoring Mail Notification script')
    da_prod_ctm_fuel_coupon_redeemer_task = BashOperator(task_id='da_prod_ctm_fuel_coupon_redeemer', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s Fuel_Coupon_Redeemer_V1/LOAD_CA0009_MBR_FUEL_REDM.sql', owner='ctmuser', doc='Start the fuel coupon redeemer job')
    da_prod_ctm_store_comparative_task = BashOperator(task_id='da_prod_ctm_store_comparative', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s Comparative_Stores/store_comparative_CURRENT.r', owner='ctmuser', doc='Run the Store Comparative Job')
    da_prod_ctm_promo_sensitivity_task = BashOperator(task_id='da_prod_ctm_promo_sensitivity', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s Promotion_Sensitivity_V1/LOAD_CA0003_MBR_PROMO_SENS_01.sql', owner='ctmuser', doc='Start the promo sensitivity job')
    da_prod_ctm_store_attribute_task = BashOperator(task_id='da_prod_ctm_store_attribute', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/software_redevelopment/cafb.git -s Store_Attributes_V1/LOAD_CA0020_STORE_01.sql', owner='ctmuser', doc='Start the store attributes job')
    da_prod_ctm_member_right_cardholder_task = BashOperator(task_id='da_prod_ctm_member_right_cardholder', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/software_redevelopment/cafb.git -s Right_Cardholders_V1/LOAD_CA0120_MBR_RIGHTCARD.sql', owner='ctmuser', doc='Start the member right cardholder job')
    da_prod_ctm_member_switch_task = BashOperator(task_id='da_prod_ctm_member_switch', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/software_redevelopment/cafb.git -s Switcher_Segments/LOAD_CA0079_MBR_SWITCHER.sql', owner='ctmuser', doc='Start the member switcher job')
    da_prod_ctm_defcon_job_task = BashOperator(task_id='da_prod_ctm_defcon_job', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/software_redevelopment/cafb.git -s Spend_Score/LOAD_CA0052_DEFCON.sql', owner='ctmuser', doc='Start the member defcon - spend score job')
    da_prod_ctm_fb_member_survey_task = BashOperator(task_id='da_prod_ctm_fb_member_survey', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s Member_Survey_V1/flat_survey_data.r', owner='ctmuser', doc='Start the member survey job')
    da_prod_ctm_fb_member_survey_export_task = BashOperator(task_id='da_prod_ctm_fb_member_survey_export', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s Member_Survey_V1/flat_survey_export.r', owner='ctmuser', doc='Start the member survey export job')
    da_prod_ctm_member_digital_preference_task = BashOperator(task_id='da_prod_ctm_member_digital_preference', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s Digital_Preference/member_digital_preference_CURRENT.r', owner='ctmuser', doc='Start the member digital preference job')
    da_prod_ctm_member_participation_segment_task = BashOperator(task_id='da_prod_ctm_member_participation_segment', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/software_redevelopment/cafb.git -s Participation_Segments_V1/LOAD_CA0158_PARTICIPATION_SEG.SQL', owner='ctmuser', doc='Start the member participation segment job')
    da_prod_ctm_load_aa0999_ck_glmn_lookup_task = BashOperator(task_id='da_prod_ctm_load_aa0999_ck_glmn_lookup', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s   Sales_Uplift_Automation_V1/load_aa0999_customer_key_glmn_lookup.r', owner='ctmuser', doc='Run the Daily job to load table aa0999_ck_glmn_lookup')
    da_prod_ctm_sales_uplift_2x_automation_task = BashOperator(task_id='da_prod_ctm_sales_uplift_2x_automation', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s   Sales_Uplift_Automation_V1/Sales_Uplift_Automation_2XAutomation_sales_uplift_DM_and_trigger_code_for_CSS.r', owner='ctmuser', doc='Run the Daily FB CTM Reps - Sales uplift automation 2x Reporting job')
    da_prod_ctm_load_kt0016_pca_refresh_task = BashOperator(task_id='da_prod_ctm_load_kt0016_pca_refresh', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/kmart/dashboards.git -s       campaign_fact/LOAD_KT0016_PCA_REFRESH.sql', owner='ctmuser', doc='Run the stored proc -Load_kt0016_PCA_refresh')
    da_prod_ctm_hcf_query_schedule_task = BashOperator(task_id='da_prod_ctm_hcf_query_schedule', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/part.git -s HCF_Report/HCF_Query_schedule.r', owner='ctmuser', doc='HCF Report to query the product file and product history and commission and transaction file for Power BI reporting')
    da_prod_ctm_hcf_campaign_profiling_report_task = BashOperator(task_id='da_prod_ctm_hcf_campaign_profiling_report', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/part.git -s HCF_Campaign_Profile_Dashboard/HCF_CampaignProfiling_schedule.r', owner='ctmuser', doc='Run HCF_Campaign_Profiling_Report')
    da_prod_ctm_coles_trade_pulse_report_task = BashOperator(task_id='da_prod_ctm_coles_trade_pulse_report', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py                                                             -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s Coles_Trade_Dashboard/Coles_Trading_Dashboard_CURRENT.r', owner='ctmuser', doc='Coles Trade Pulse Report designed to give an overview of market dynamics in Coles')
    da_prod_ctm_tena_email_trigger_task = BashOperator(task_id='da_prod_ctm_tena_email_trigger', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py          -p R -r gitlab.com/flybuys_analytics/software_redevelopment/cafb.git               -s TENA_Email_Trigger/Tena_Email_Trigger_report_CURRENT.r', owner='ctmuser', doc='Tena Email Trigger Job')
    da_prod_ctm_load_pr0313_points_balance_dim2_task = BashOperator(task_id='da_prod_ctm_load_pr0313_points_balance_dim2', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/PR0313_Historical_Points_Balance.git -s        LOAD_PR0313_POINTS_BALANCE_DIM2.sql', owner='ctmuser', doc='Run the stored proc- LOAD_PR0313_POINTS_BALANCE_DIM2.sql')
    da_prod_ctm_load_card_rdm_active_dim_task = BashOperator(task_id='da_prod_ctm_load_card_rdm_active_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0325_active_cards.git -s        LOAD_CARD_RDM_ACTIVE_DIM.sql', owner='ctmuser', doc='Run the stored proc LOAD_CARD_RDM_ACTIVE_DIM.sql - Redemption Activity Status Job')
    da_prod_ctm_load_card_active_dim_task = BashOperator(task_id='da_prod_ctm_load_card_active_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0325_active_cards.git -s        LOAD_CARD_ACTIVE_DIM.sql', owner='ctmuser', doc='Run the stored proc LOAD_CARD_ACTIVE_DIM.sql - Card 52 Activity Status Job')
    da_prod_ctm_load_card_active_6_wk_dim_task = BashOperator(task_id='da_prod_ctm_load_card_active_6_wk_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0325_active_cards.git -s        LOAD_CARD_ACTIVE_6WK_DIM.sql', owner='ctmuser', doc='Run the stored proc LOAD_CARD_ACTIVE_6WK_DIM.sql - Card Activity Status Job')
    da_prod_ctm_load_first_scan_dim_task = BashOperator(task_id='da_prod_ctm_load_first_scan_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0303_acq_report2.git -s        store_proc_first_scan.sql', owner='ctmuser', doc='Run the stored proc- LOAD_FIRST_SCAN_DIM')
    da_prod_ctm_load_acquisition_dashboard_task = BashOperator(task_id='da_prod_ctm_load_acquisition_dashboard', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0303_acq_report2.git -s        store_proc_load_acquisition_dashboard.sql', owner='ctmuser', doc='Run the stored proc- LOAD_ACQUISITION_DASHBOARD')
    da_prod_ctm_load_kt071_promo_assignment_task = BashOperator(task_id='da_prod_ctm_load_kt071_promo_assignment', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/kmart/dashboards.git -s              campaign_fact/LOAD_KT071_PROMO_ASSIGNMENT.SQL', owner='ctmuser', doc='Run the stored proc - LOAD_KT071_PROMO_ASSIGNMENT.sql')
    da_prod_ctm_feature_load_card_app_active_30_d_dim_task = BashOperator(task_id='da_prod_ctm_feature_load_card_app_active_30_d_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s          App_Activity/LOAD_CARD_APP_ACTIVE_30D_DIM.sql', owner='ctmuser', doc='Run the stored proc - LOAD_CARD_APP_ACTIVE_30D_DIM.sql')
    da_prod_ctm_feature_load_card_app_active_12_w_dim_task = BashOperator(task_id='da_prod_ctm_feature_load_card_app_active_12_w_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s              App_Activity/LOAD_CARD_APP_ACTIVE_12W_DIM.sql', owner='ctmuser', doc='Run the stored proc - LOAD_CARD_APP_ACTIVE_12W_DIM.sql')
    da_prod_ctm_feature_load_card_app_active_6_m_dim_task = BashOperator(task_id='da_prod_ctm_feature_load_card_app_active_6_m_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s              App_Activity/LOAD_CARD_APP_ACTIVE_6M_DIM.sql', owner='ctmuser', doc='Run the stored proc - LOAD_CARD_APP_ACTIVE_6M_DIM.sql')
    da_prod_ctm_feature_load_card_app_active_9_m_dim_task = BashOperator(task_id='da_prod_ctm_feature_load_card_app_active_9_m_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s              App_Activity/LOAD_CARD_APP_ACTIVE_9M_DIM.sql', owner='ctmuser', doc='Run the stored proc - LOAD_CARD_APP_ACTIVE_9M_DIM.sql')
    da_prod_ctm_feature_load_card_app_active_dim_task = BashOperator(task_id='da_prod_ctm_feature_load_card_app_active_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s              App_Activity/LOAD_CARD_APP_ACTIVE_DIM.sql', owner='ctmuser', doc='Run the stored proc - LOAD_CARD_APP_ACTIVE_DIM.sql')
    da_prod_ctm_feature_load_close_date_dim_task = BashOperator(task_id='da_prod_ctm_feature_load_close_date_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s              close_date/LOAD_CLOSE_DATE_DIM.sql', owner='ctmuser', doc='Run the stored proc - LOAD_CLOSE_DATE_DIM.sql')
    da_prod_ctm_feature_load_mbr_52_w_lic_count_dim_task = BashOperator(task_id='da_prod_ctm_feature_load_mbr_52_w_lic_count_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s          number_of_partners/LOAD_MBR_52W_LIC_COUNT_DIM.sql', owner='ctmuser', doc='Run the stored proc - LOAD_MBR_52W_LIC_COUNT_DIM.sql')
    da_prod_ctm_feature_load_card_active_process_dim_task = BashOperator(task_id='da_prod_ctm_feature_load_card_active_process_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s              active_cards_process_date/LOAD_CARD_ACTIVE_PROCESS_DIM.sql', owner='ctmuser', doc='Run the stored proc - LOAD_CARD_ACTIVE_PROCESS_DIM.sql')
    da_prod_ctm_feature_load_52wk_bonus_active_dim_task = BashOperator(task_id='da_prod_ctm_feature_load_52wk_bonus_active_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         Bonus_Points_Earners/LOAD_52WK_BONUS_ACTIVE_DIM.sql', owner='ctmuser', doc='Run the stored proc - LOAD_52WK_BONUS_ACTIVE_DIM.sql')
    da_prod_ctm_feature_load_52wk_bonus_active_dim_proc_task = BashOperator(task_id='da_prod_ctm_feature_load_52wk_bonus_active_dim_proc', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         Bonus_Points_Earners/LOAD_52WK_BONUS_ACTIVE_DIM_PROC.sql', owner='ctmuser', doc='Run the stored proc - LOAD_52WK_BONUS_ACTIVE_DIM_PROC.sql')
    da_prod_ctm_feature_load_24_wk_bonus_active_dim_task = BashOperator(task_id='da_prod_ctm_feature_load_24_wk_bonus_active_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         Bonus_Points_Earners/LOAD_24WK_BONUS_ACTIVE_DIM.sql', owner='ctmuser', doc='Run the stored proc - LOAD_24WK_BONUS_ACTIVE_DIM.sql')
    da_prod_ctm_feature_load_24_wk_bonus_active_dim_proc_task = BashOperator(task_id='da_prod_ctm_feature_load_24_wk_bonus_active_dim_proc', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         Bonus_Points_Earners/LOAD_24WK_BONUS_ACTIVE_DIM_PROC.sql', owner='ctmuser', doc='Run the stored proc - LOAD_24WK_BONUS_ACTIVE_DIM_PROC.sql')
    da_prod_ctm_feature_load_12_wk_bonus_active_dim_task = BashOperator(task_id='da_prod_ctm_feature_load_12_wk_bonus_active_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         Bonus_Points_Earners/LOAD_12WK_BONUS_ACTIVE_DIM.sql', owner='ctmuser', doc='Run the stored proc - LOAD_12WK_BONUS_ACTIVE_DIM.sql')
    da_prod_ctm_feature_load_12_wk_bonus_active_dim_proc_task = BashOperator(task_id='da_prod_ctm_feature_load_12_wk_bonus_active_dim_proc', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         Bonus_Points_Earners/LOAD_12WK_BONUS_ACTIVE_DIM_PROC.sql', owner='ctmuser', doc='Run the stored proc - LOAD_12WK_BONUS_ACTIVE_DIM_PROC.sql')
    da_prod_ctm_feature_load_12_wk_5000_bonus_active_dim_task = BashOperator(task_id='da_prod_ctm_feature_load_12_wk_5000_bonus_active_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         Bonus_Points_Earners/LOAD_12WK_5000_BONUS_ACTIVE_DIM.sql', owner='ctmuser', doc='Run the stored proc - LOAD_12WK_5000_BONUS_ACTIVE_DIM.sql')
    da_prod_ctm_feature_load_12_wk_5000_bonus_active_dim_proc_task = BashOperator(task_id='da_prod_ctm_feature_load_12_wk_5000_bonus_active_dim_proc', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         Bonus_Points_Earners/LOAD_12WK_5000_BONUS_ACTIVE_DIM_PROC.sql', owner='ctmuser', doc='Run the stored proc - LOAD_12WK_5000_BONUS_ACTIVE_DIM_PROC.sql')
    da_prod_ctm_feature_load_12_wk_st_active_dim_task = BashOperator(task_id='da_prod_ctm_feature_load_12_wk_st_active_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         Standard_Pts_6wks/LOAD_12WK_ST_ACTIVE_DIM.sql', owner='ctmuser', doc='Run the stored proc - LOAD_12WK_ST_ACTIVE_DIM.sql')
    da_prod_ctm_feature_load_12_wk_cfs_active_dim_task = BashOperator(task_id='da_prod_ctm_feature_load_12_wk_cfs_active_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         cfs_12wks/LOAD_12WK_CFS_ACTIVE_DIM.sql', owner='ctmuser', doc='Run the stored proc - LOAD_12WK_CFS_ACTIVE_DIM.sql')
    da_prod_ctm_feature_load_52_wks_vff_active_dim2_task = BashOperator(task_id='da_prod_ctm_feature_load_52_wks_vff_active_dim2', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         vff_last52wks/LOAD_52WKS_VFF_ACTIVE_DIM2.sql', owner='ctmuser', doc='Run the stored proc - LOAD_52WKS_VFF_ACTIVE_DIM2.sql')
    da_prod_ctm_feature_load_3_y_redeemed_dim2_task = BashOperator(task_id='da_prod_ctm_feature_load_3_y_redeemed_dim2', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         3_yr_redeemed/LOAD_3Y_REDEEMED_DIM2.sql', owner='ctmuser', doc='Run the stored proc - LOAD_3Y_REDEEMED_DIM2.sql')
    da_prod_ctm_feature_load_4_w_lapsing_dim2_task = BashOperator(task_id='da_prod_ctm_feature_load_4_w_lapsing_dim2', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         Lapsing_data/LOAD_4W_LAPSING_DIM2.sql', owner='ctmuser', doc='Run the stored proc - LOAD_4W_LAPSING_DIM2.sql')
    da_prod_ctm_feature_load_offer_activation_1_dim2_task = BashOperator(task_id='da_prod_ctm_feature_load_offer_activation_1_dim2', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         campaign_activation/LOAD_OFFER_ACTIVATION_1_DIM2.sql', owner='ctmuser', doc='Run the stored proc - LOAD_OFFER_ACTIVATION_1_DIM2.sql')
    da_prod_ctm_feature_load_offer_activation_3_dim2_task = BashOperator(task_id='da_prod_ctm_feature_load_offer_activation_3_dim2', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         campaign_activation/LOAD_OFFER_ACTIVATION_3_DIM2.sql', owner='ctmuser', doc='Run the stored proc - LOAD_OFFER_ACTIVATION_3_DIM2.sql')
    da_prod_ctm_feature_load_offer_activation_5_dim2_task = BashOperator(task_id='da_prod_ctm_feature_load_offer_activation_5_dim2', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         campaign_activation/LOAD_OFFER_ACTIVATION_5_DIM2.sql', owner='ctmuser', doc='Run the stored proc - LOAD_OFFER_ACTIVATION_5_DIM2.sql')
    da_prod_ctm_feature_load_card_active_dim_proc_task = BashOperator(task_id='da_prod_ctm_feature_load_card_active_dim_proc', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         active_cards_process_date/LOAD_CARD_ACTIVE_DIM_PROC.sql', owner='ctmuser', doc='Run the stored proc - LOAD_CARD_ACTIVE_DIM_PROC.sql')
    da_prod_ctm_feature_load_card_active_24_wk_dim_proc_task = BashOperator(task_id='da_prod_ctm_feature_load_card_active_24_wk_dim_proc', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         active_cards_process_date/LOAD_CARD_ACTIVE_24WK_DIM_PROC.sql', owner='ctmuser', doc='Run the stored proc - LOAD_CARD_ACTIVE_24WK_DIM_PROC.sql')
    da_prod_ctm_feature_load_card_active_12_wk_dim_proc_task = BashOperator(task_id='da_prod_ctm_feature_load_card_active_12_wk_dim_proc', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         active_cards_process_date/LOAD_CARD_ACTIVE_12WK_DIM_PROC.sql', owner='ctmuser', doc='Run the stored proc - LOAD_CARD_ACTIVE_12WK_DIM_PROC.sql')
    da_prod_ctm_feature_load_card_active_6_wk_dim_proc_task = BashOperator(task_id='da_prod_ctm_feature_load_card_active_6_wk_dim_proc', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         active_cards_process_date/LOAD_CARD_ACTIVE_6WK_DIM_PROC.sql', owner='ctmuser', doc='Run the stored proc - LOAD_CARD_ACTIVE_6WK_DIM_PROC.sql')
    da_prod_ctm_feature_load_card_active_lic_52_wk_dim_task = BashOperator(task_id='da_prod_ctm_feature_load_card_active_lic_52_wk_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         Active_Licensee_Number/LOAD_CARD_ACTIVE_LIC_52WK_DIM.sql', owner='ctmuser', doc='Run the stored proc - LOAD_CARD_ACTIVE_LIC_52WK_DIM.sql')
    da_prod_ctm_feature_load_card_active_lic_12_wk_dim_task = BashOperator(task_id='da_prod_ctm_feature_load_card_active_lic_12_wk_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         Active_Licensee_Number/LOAD_CARD_ACTIVE_LIC_12WK_DIM.sql', owner='ctmuser', doc='Run the stored proc - LOAD_CARD_ACTIVE_LIC_12WK_DIM.sql')
    da_prod_ctm_feature_load_mbr_52_wk_lic_count_proc_dim_task = BashOperator(task_id='da_prod_ctm_feature_load_mbr_52_wk_lic_count_proc_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s         number_of_partners/LOAD_MBR_52W_LIC_COUNT_PROC_DIM.sql', owner='ctmuser', doc='Run the stored proc - LOAD_MBR_52W_LIC_COUNT_PROC_DIM.sql')
    da_prod_ctm_coalition_feature_table_task = BashOperator(task_id='da_prod_ctm_coalition_feature_table', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/part.git -s         Coalition_Features_Table/Coalition_Feature_Query.r', owner='ctmuser', doc='Run the job - CTM_Coalition_Feature_Table')
    da_prod_ctm_coalition_discovery_parks_query_task = BashOperator(task_id='da_prod_ctm_coalition_discovery_parks_query', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/part.git -s         Coalition_Partner_Query/Discovery_Parks_Query.R', owner='ctmuser', doc='Run the job - CTM_Discovery_Parks_Coalition_Query')
    da_prod_ctm_welcome_series_trigger_2_0_task = BashOperator(task_id='da_prod_ctm_welcome_series_trigger_2.0', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/PROG.git -s         Welcome_Series_2/Welcome_Series_2_0_Test_Mbrs_Email_trigger.r', owner='ctmuser', doc='Welcome Series Trigger 2.0')
    da_prod_ctm_rewards_automated_banners_task = BashOperator(task_id='da_prod_ctm_rewards_automated_banners', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/PROG.git -s         Rewards/REWARDS_AUTOMATED_BANNERS/FULFILMENT_EMAIL_TRIGGERS.r', owner='ctmuser', doc='Rewards Automated Banners')
    da_prod_ctm_pure_profile_query_task = BashOperator(task_id='da_prod_ctm_pure_profile_query', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py           -p R -r gitlab.com/flybuys_analytics/software_redevelopment/part.git -s \\Coalition_Partner_Query/PureProfile_Query.R', owner='ctmuser', doc='Run the PureProfile Query - daily Job')
    da_prod_ctm_mycar_query_task = BashOperator(task_id='da_prod_ctm_mycar_query', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py           -p R -r gitlab.com/flybuys_analytics/software_redevelopment/part.git -s \\Coalition_Partner_Query/MyCar_Query.R', owner='ctmuser', doc='Run the Mycar Query - daily Job')
    da_prod_ctm_welcome_series_beb_code_2_0_task = BashOperator(task_id='da_prod_ctm_welcome_series_beb_code_2_0', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py           -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s \\Welcome_Series_2/Welcome_Series_BEB_code_2_0.r', owner='ctmuser', doc='Run the WelcomeSeries_BEB_Code_2_0 - daily Job')
    da_prod_ctm_velocity_ff_query_task = BashOperator(task_id='da_prod_ctm_velocity_ff_query', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/part.git -s         Coalition_Partner_Query/VFF_Query.r', owner='ctmuser', doc='Run the job - Velocity_FF_Query')
    da_prod_ctm_clg_birthday_triggers_task = BashOperator(task_id='da_prod_ctm_clg_birthday_triggers', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s         CLG_Birthday_triggers/LQ_Birthday_triggers.r', owner='ctmuser', doc='Run the job - Coles Liquor Group Birthday Triggers')
    da_prod_ctm_feature_load_12_wk_cfs_active_dim_proc_task = BashOperator(task_id='da_prod_ctm_feature_load_12_wk_cfs_active_dim_proc', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s          cfs_12wks/LOAD_12WK_CFS_ACTIVE_DIM_PROC.sql', owner='ctmuser', doc='Run the stored proc - LOAD_12WK_CFS_ACTIVE_DIM_PROC.sql')
    da_prod_ctm_feature_load_4_wk_std_active_dim_proc_task = BashOperator(task_id='da_prod_ctm_feature_load_4_wk_std_active_dim_proc', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s              Standard_Pts_6wks/LOAD_4WK_ST_ACTIVE_DIM_PROC.sql', owner='ctmuser', doc='Run the stored proc - LOAD_4WK_ST_ACTIVE_DIM_PROC.sql')
    da_prod_ctm_feature_load_12_wk_std_active_dim_proc_task = BashOperator(task_id='da_prod_ctm_feature_load_12_wk_std_active_dim_proc', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s              Standard_Pts_6wks/LOAD_12WK_ST_ACTIVE_DIM_PROC.sql', owner='ctmuser', doc='Run the stored proc - LOAD_CARD_APP_ACTIVE_6M_DIM.sql')
    da_prod_ctm_liquor_birthday_triggers_task = BashOperator(task_id='da_prod_ctm_liquor_birthday_triggers', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/secured/cafb.git -s              Liquor_Birthday_Trigger_placeholder/Liquor_Birthday_Triggers_CURRENT.R', owner='ctmuser', doc='Run the stored proc - Liquor_Birthday_Triggers')
    da_prod_ctm_load_6_wk_bonus_active_dim_proc_task = BashOperator(task_id='da_prod_ctm_load_6_wk_bonus_active_dim_proc', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s        Bonus_Points_Earners/LOAD_6WK_BONUS_ACTIVE_DIM_PROC.sql', owner='ctmuser', doc='Run the stored proc- LOAD_6WK_BONUS_ACTIVE_DIM_PROC.sql')
    da_prod_ctm_load_card_app_active_6_w_dim_task = BashOperator(task_id='da_prod_ctm_load_card_app_active_6_w_dim', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s        App_Activity/LOAD_CARD_APP_ACTIVE_6W_DIM.sql', owner='ctmuser', doc='Run the stored proc- LOAD_CARD_APP_ACTIVE_6W_DIM.sql')
    da_prod_ctm_load_offer_activation_1_6_wks_dim2_task = BashOperator(task_id='da_prod_ctm_load_offer_activation_1_6_wks_dim2', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p Python -r gitlab.com/flybuys_analytics/program/pr0345_program_feature_stores2.git -s        campaign_activation/LOAD_OFFER_ACTIVATION_1_6WKS_DIM2.sql', owner='ctmuser', doc='Run the stored proc- LOAD_OFFER_ACTIVATION_1_6WKS_DIM2.sql')
    da_prod_ctm_flybuys_travel_query_task = BashOperator(task_id='da_prod_ctm_flybuys_travel_query', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/part.git -s         Coalition_Partner_Query/Flybuys_Travel_Query.r', owner='ctmuser', doc='Run the job - Flybuys_Travel_Query')
    da_prod_ctm_leggos_dashboard_trigger_task = BashOperator(task_id='da_prod_ctm_leggos_dashboard_trigger', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py          -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git           -s Leggos_Dashboard_Trigger/leggos_dashboard_trigger_v1.R', owner='ctmuser', doc='Leggos_Dashboard_Trigger')
    da_prod_ctm_cp010_coalition_overall_task = BashOperator(task_id='da_prod_ctm_cp010_coalition_overall', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/part.git -s Coalition_Partner_Query/Coalition_Overall.R', owner='ctmuser', doc='Run the Coalition Overall Job')
    da_prod_ctm_one_pass_5x_points_daily_report_task = BashOperator(task_id='da_prod_ctm_one_pass_5x_points_daily_report', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/part.git -s OnePass_5x_Dashboard/OnePass_Daily_Report.r', owner='ctmuser', doc='Run the OnePass_5xPoints_Daily_Report Job')
    da_prod_ctm_hcf_campaign_query_task = BashOperator(task_id='da_prod_ctm_hcf_campaign_query', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/part.git -s Coalition_Partner_Query/HCF_Campaign_Query.r', owner='ctmuser', doc='HCF Campaign Query for Power BI')
    da_prod_ctm_hcf_dashboard_query_task = BashOperator(task_id='da_prod_ctm_hcf_dashboard_query', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/part.git -s Coalition_Partner_Query/HCF_Dashboard_Query.R', owner='ctmuser', doc='HCF Dashboard Query for Power BI')
    da_prod_ctm_cdm_ingestion_monitor_bucket_1_task >> da_prod_ctm_defcon_job_task
    da_prod_ctm_cdm_ingestion_monitor_bucket_1_task >> da_prod_ctm_fb_12_month_active_mbr_task
    da_prod_ctm_cdm_ingestion_monitor_bucket_1_task >> da_prod_ctm_member_switch_task
    da_prod_ctm_cdm_ingestion_monitor_bucket_1_task >> da_prod_ctm_rfm_coles_scoring_main_task
    da_prod_ctm_cdm_ingestion_monitor_bucket_1_task >> da_prod_ctm_store_attribute_task
    da_prod_ctm_cdm_ingestion_monitor_bucket_1_task >> da_prod_ctm_tena_email_trigger_task
    da_prod_ctm_cdm_ingestion_monitor_bucket_3_task >> da_prod_ctm_rfm_coles_scoring_main_task
    da_prod_ctm_ciw_ingestion_monitor_coles_bucket_1_task >> da_prod_ctm_defcon_job_task
    da_prod_ctm_ciw_ingestion_monitor_coles_bucket_1_task >> da_prod_ctm_fb_12_month_active_mbr_task
    da_prod_ctm_ciw_ingestion_monitor_coles_bucket_1_task >> da_prod_ctm_fuel_coupon_redeemer_task
    da_prod_ctm_ciw_ingestion_monitor_coles_bucket_1_task >> da_prod_ctm_load_first_scan_dim_task
    da_prod_ctm_ciw_ingestion_monitor_coles_bucket_1_task >> da_prod_ctm_member_switch_task
    da_prod_ctm_ciw_ingestion_monitor_coles_bucket_1_task >> da_prod_ctm_promo_sensitivity_task
    da_prod_ctm_ciw_ingestion_monitor_coles_bucket_1_task >> da_prod_ctm_rfm_coles_scoring_main_task
    da_prod_ctm_ciw_ingestion_monitor_coles_bucket_1_task >> da_prod_ctm_sales_uplift_2x_automation_task
    da_prod_ctm_ciw_ingestion_monitor_coles_bucket_1_task >> da_prod_ctm_store_attribute_task
    da_prod_ctm_ciw_ingestion_monitor_coles_bucket_1_task >> da_prod_ctm_store_comparative_task
    da_prod_ctm_ciw_ingestion_monitor_coles_bucket_1_task >> da_prod_ctm_tena_email_trigger_task
    da_prod_ctm_ciw_ingestion_monitor_coles_bucket_2_task >> da_prod_ctm_load_aa0999_ck_glmn_lookup_task
    da_prod_ctm_clg_birthday_triggers_task >> da_prod_ctm_liquor_birthday_triggers_task
    da_prod_ctm_coalition_discovery_parks_query_task >> da_prod_ctm_cp010_coalition_overall_task
    da_prod_ctm_fb_12_month_active_cardholder_task >> da_prod_ctm_clg_birthday_triggers_task
    da_prod_ctm_fb_12_month_active_cardholder_task >> da_prod_ctm_coalition_discovery_parks_query_task
    da_prod_ctm_fb_12_month_active_cardholder_task >> da_prod_ctm_coalition_feature_table_task
    da_prod_ctm_fb_12_month_active_cardholder_task >> da_prod_ctm_coles_trade_pulse_report_task
    da_prod_ctm_fb_12_month_active_cardholder_task >> da_prod_ctm_fb_12month_active_volume_mail_notif_task
    da_prod_ctm_fb_12_month_active_cardholder_task >> da_prod_ctm_flybuys_travel_data_refresh_task
    da_prod_ctm_fb_12_month_active_cardholder_task >> da_prod_ctm_rewards_automated_banners_task
    da_prod_ctm_fb_12_month_active_cardholder_task >> da_prod_ctm_tena_email_trigger_task
    da_prod_ctm_fb_12_month_active_cardholder_task >> da_prod_ctm_velocity_ff_query_task
    da_prod_ctm_fb_12_month_active_mbr_task >> da_prod_ctm_fb_12_month_active_cardholder_task
    da_prod_ctm_fb_12_month_active_mbr_task >> da_prod_ctm_fb_active_12_m_mbr_cs_export_task
    da_prod_ctm_fb_12_month_active_mbr_task >> da_prod_ctm_liquor_birthday_triggers_task
    da_prod_ctm_fb_12_month_active_mbr_task >> da_prod_ctm_rewards_automated_banners_task
    da_prod_ctm_fb_member_survey_task >> da_prod_ctm_fb_member_survey_export_task
    da_prod_ctm_flybuys_travel_customer_journey_main_task >> da_prod_ctm_flybuys_travel_customer_journey_mail_notification_task
    da_prod_ctm_flybuys_travel_data_refresh_task >> da_prod_ctm_travel_search_trigger_task
    da_prod_ctm_flybuys_travel_query_task >> da_prod_ctm_cp010_coalition_overall_task
    da_prod_ctm_fuel_coupon_redeemer_task >> da_prod_ctm_member_right_cardholder_task
    da_prod_ctm_hcf_dashboard_query_task >> da_prod_ctm_hcf_campaign_query_task
    da_prod_ctm_load_card_active_dim_task >> da_prod_ctm_load_acquisition_dashboard_task
    da_prod_ctm_load_first_scan_dim_task >> da_prod_ctm_load_acquisition_dashboard_task
    da_prod_ctm_member_switch_task >> da_prod_ctm_member_right_cardholder_task
    da_prod_ctm_mycar_query_task >> da_prod_ctm_cp010_coalition_overall_task
    da_prod_ctm_promo_sensitivity_task >> da_prod_ctm_member_right_cardholder_task
    da_prod_ctm_pure_profile_query_task >> da_prod_ctm_cp010_coalition_overall_task
    da_prod_ctm_rfm_coles_scoring_main_task >> da_prod_ctm_rfm_coles_scoring_mail_notification_task
    da_prod_ctm_store_attribute_task >> da_prod_ctm_member_switch_task
    da_prod_ctm_velocity_ff_query_task >> da_prod_ctm_cp010_coalition_overall_task
    da_prod_sotday_task >> da_prod_ctm_cdm_ingestion_monitor_bucket_1_task
    da_prod_sotday_task >> da_prod_ctm_cdm_ingestion_monitor_bucket_3_task
    da_prod_sotday_task >> da_prod_ctm_ciw_ingestion_monitor_coles_bucket_1_task
    da_prod_sotday_task >> da_prod_ctm_ciw_ingestion_monitor_coles_bucket_2_task
    da_prod_sotday_task >> da_prod_ctm_fb_member_survey_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_12_wk_5000_bonus_active_dim_proc_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_12_wk_5000_bonus_active_dim_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_12_wk_bonus_active_dim_proc_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_12_wk_bonus_active_dim_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_12_wk_cfs_active_dim_proc_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_12_wk_cfs_active_dim_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_12_wk_st_active_dim_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_12_wk_std_active_dim_proc_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_24_wk_bonus_active_dim_proc_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_24_wk_bonus_active_dim_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_3_y_redeemed_dim2_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_4_w_lapsing_dim2_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_4_wk_std_active_dim_proc_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_52_wks_vff_active_dim2_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_52wk_bonus_active_dim_proc_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_52wk_bonus_active_dim_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_card_active_12_wk_dim_proc_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_card_active_24_wk_dim_proc_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_card_active_6_wk_dim_proc_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_card_active_dim_proc_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_card_active_lic_12_wk_dim_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_card_active_lic_52_wk_dim_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_card_active_process_dim_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_card_app_active_12_w_dim_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_card_app_active_30_d_dim_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_card_app_active_6_m_dim_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_card_app_active_9_m_dim_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_card_app_active_dim_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_close_date_dim_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_mbr_52_w_lic_count_dim_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_mbr_52_wk_lic_count_proc_dim_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_offer_activation_1_dim2_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_offer_activation_3_dim2_task
    da_prod_sotday_task >> da_prod_ctm_feature_load_offer_activation_5_dim2_task
    da_prod_sotday_task >> da_prod_ctm_flybuys_travel_customer_journey_main_task
    da_prod_sotday_task >> da_prod_ctm_flybuys_travel_query_task
    da_prod_sotday_task >> da_prod_ctm_hcf_campaign_profiling_report_task
    da_prod_sotday_task >> da_prod_ctm_hcf_campaign_query_task
    da_prod_sotday_task >> da_prod_ctm_hcf_dashboard_query_task
    da_prod_sotday_task >> da_prod_ctm_hcf_query_schedule_task
    da_prod_sotday_task >> da_prod_ctm_leggos_dashboard_trigger_task
    da_prod_sotday_task >> da_prod_ctm_load_6_wk_bonus_active_dim_proc_task
    da_prod_sotday_task >> da_prod_ctm_load_card_active_6_wk_dim_task
    da_prod_sotday_task >> da_prod_ctm_load_card_active_dim_task
    da_prod_sotday_task >> da_prod_ctm_load_card_app_active_6_w_dim_task
    da_prod_sotday_task >> da_prod_ctm_load_card_rdm_active_dim_task
    da_prod_sotday_task >> da_prod_ctm_load_kt0016_pca_refresh_task
    da_prod_sotday_task >> da_prod_ctm_load_kt071_promo_assignment_task
    da_prod_sotday_task >> da_prod_ctm_load_offer_activation_1_6_wks_dim2_task
    da_prod_sotday_task >> da_prod_ctm_load_pr0313_points_balance_dim2_task
    da_prod_sotday_task >> da_prod_ctm_member_digital_preference_task
    da_prod_sotday_task >> da_prod_ctm_member_participation_segment_task
    da_prod_sotday_task >> da_prod_ctm_mycar_query_task
    da_prod_sotday_task >> da_prod_ctm_one_pass_5x_points_daily_report_task
    da_prod_sotday_task >> da_prod_ctm_pure_profile_query_task
    da_prod_sotday_task >> da_prod_ctm_welcome_series_beb_code_2_0_task
    da_prod_sotday_task >> da_prod_ctm_welcome_series_trigger_2_0_task