from airflow import DAG
from airflow.operators.bash import BashOperator
from pendulum import DateTime

with DAG(dag_id='da_prod_data_and_analytics_scdm_daily', schedule=None, start_date=DateTime(1970, 1, 1, 0, 0, 0), catchup=False):
    da_prod_scdm_precheck_dn_a_task = BashOperator(task_id='da_prod_scdm_precheck_dn_a', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s SCDM/Precheck/Precheck_DnA_Script.R', owner='ctmuser', doc='Precheck for DnA')
    da_prod_scdm_precheck_sf2_rds_task = BashOperator(task_id='da_prod_scdm_precheck_sf2_rds', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s SCDM/Precheck/Precheck_SF2RDS_Script.R', owner='ctmuser', doc='Check the dependency from SF to RDS')
    da_prod_scdm_response_task = BashOperator(task_id='da_prod_scdm_response', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s SCDM/Response/scdm_response_CURRENT.r', owner='ctmuser', doc='This program tracks the campaign response across various partners and records loads in a log table, while sending out a notification mail along with the summary of the load.')
    da_prod_scdm_activation_mbb_task = BashOperator(task_id='da_prod_scdm_activation_mbb', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s SCDM/Activation/activation_mbr_CURRENT.r', owner='ctmuser', doc='This program do the data preparation for scdm activation loading.')
    da_prod_scdm_activation_task = BashOperator(task_id='da_prod_scdm_activation', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s SCDM/Activation/scdm_activation_CURRENT.r', owner='ctmuser', doc='This program tracks the campaign activations across various partners and records loads in a log table, while sending out a notification mail along with the summary of the load.')
    da_prod_ctm_scdmciw_update_task = BashOperator(task_id='da_prod_ctm_scdmciw_update', bash_command='. /home/controlm/analytics-jobs/env/set_env.sh; python3 /home/controlm/analytics-jobs/utility/docker-git-wrapper.py         -p R -r gitlab.com/flybuys_analytics/software_redevelopment/prog.git -s SCDM/Transaction/scdm_transaction_hist_update_CURRENT.r', owner='ctmuser', doc='SCDM CIW Coles transaction history update')
    da_prod_scdm_activation_mbb_task >> da_prod_scdm_activation_task
    da_prod_scdm_precheck_sf2_rds_task >> da_prod_ctm_scdmciw_update_task
    da_prod_scdm_precheck_sf2_rds_task >> da_prod_scdm_activation_mbb_task
    da_prod_scdm_precheck_sf2_rds_task >> da_prod_scdm_response_task